### ISSUE TITLE
Error: failed to start xpra

### ISSUE THREAD

**Issue by Stoxis** [Amir1453/obsidicrypt#1]
I set it up per your instructions and it originally was working, then I tried to add the Xpra flag to my KeepassXC launcher and this caused Obsidian AND KeepassXC to be unable to launch. I restarted and tried to open Obsidian with the flag and now that app won't launch at all anymore unless I remove the --x11 flag from the launcher.

Log:
```
$ firejail --x11 --appimage --profile=/etc/firejail/obsidian.profile /opt/Obsidian-1.3.3.AppImage
2023-05-23 20:06:59,803 cannot use uinput for virtual devices:
2023-05-23 20:06:59,803  [Errno 2] Failed to open the uinput device: No such file or directory. Perhaps load the uinput kernel module first?
xauth:  /home/Theta/.Xauthority not writable, changes will be ignored
xauth:  /home/Theta/.Xauthority not writable, changes ignored
_XSERVTransSocketCreateListener: failed to bind listener
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: failed to create listener for unix
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
2023-05-23 20:07:02,963 Error: failed to connect to display :730
2023-05-23 20:07:02,963  could not connect to X server on display ':730' after 3 seconds
Error: failed to start xpra
```

**Comment by Amir1453** [comment]
Few things to check here:

1. Are you on Wayland or X11? If you are on Wayland, you do not need Xpra.
2. How was Xpra installed? The installation instruction might change from distro to distro
3. To test whether Xpra is working, issue the following commands on your terminal:
```sh
xpra start :100 
DISPLAY=:100 firefox
xpra attach :100
```
An Xpra window should popup, with Firefox inside of it. To stop it,
```sh
xpra stop :100
```
This is likely a problem with firejail, since there are messages regarding Xpra.
4. Try to specify `--x11=xpra` when running firejail
5. Make sure that the obsidian.profile is created properly, check whether you have the electron profile also.
6. If nothing works, uninstall Xpra and run the firejail command again. It will ask you to download either Xpra or Xephyr, try installing Xephyr and see if it works for you.
7. If nothing works, I would suggest creating an issue in the firejail repository.

Let me know how you progress!

**Comment by Amir1453** [comment]
Also check this link out, might be related: https://github.com/netblue30/firejail/discussions/4244#discussioncomment-700148

**Comment by Stoxis** [comment]
1. Are you on Wayland or X11? If you are on Wayland, you do not need Xpra.
I use MX Linux which uses X11, I verified with the terminal before installing Xpra.
2. How was Xpra installed? The installation instruction might change from distro to distro
`sudo apt-get install xpra`
3. To test whether Xpra is working, issue the following commands on your terminal:
```
Theta@Theta:~
$ xpra start :100 
Entering daemon mode; any further errors will be reported to:
  /run/user/1000/xpra/:100.log
```
:100.log
```
2023-05-24 23:12:59,693 cannot use uinput for virtual devices:[0m
2023-05-24 23:12:59,694  [Errno 2] Failed to open the uinput device: No such file or directory. Perhaps load the uinput kernel module first?[0m
xauth:  /home/Theta/.Xauthority not writable, changes will be ignored
xauth:  /home/Theta/.Xauthority not writable, changes ignored
_XSERVTransSocketCreateListener: failed to bind listener
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: failed to create listener for unix
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
[31m2023-05-24 23:13:02,765 Error: failed to connect to display :100[0m
[31m2023-05-24 23:13:02,765  could not connect to X server on display ':100' after 3 seconds[0m

```
```
Theta@Theta:~
$ DISPLAY=:100 firefox
Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/whitelist-usr-share-common.inc
Reading profile /etc/firejail/firefox-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-proc.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-run-common.inc
Reading profile /etc/firejail/whitelist-runuser-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Warning: networking feature is disabled in Firejail configuration file
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
Parent pid 27118, child pid 27121
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Warning: NVIDIA card detected, nogroups command ignored
Warning: NVIDIA card detected, nogroups command ignored
Warning: NVIDIA card detected, nogroups command ignored
Warning: NVIDIA card detected, nogroups command ignored
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
Warning: NVIDIA card detected, nogroups command ignored
Warning: NVIDIA card detected, nogroups command ignored
Warning: Replacing profile instead of stacking it. It is a legacy behavior that can result in relaxation of the protection. It is here as a temporary measure to unbreak the software that has been broken by switching to the stacking behavior.
Child process initialized in 112.93 ms
No protocol specified
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :100

Parent is shutting down, bye...
```
Firefox launches fine without Xpra, it only fails when I try to use that command.
4. Try to specify --x11=xpra when running firejail
```
Theta@Theta:~
$ firejail --x11=xpra --appimage --profile=/etc/firejail/obsidian.profile /opt/Obsidian-1.3.3.AppImage
2023-05-24 23:18:57,926 cannot use uinput for virtual devices:
2023-05-24 23:18:57,926  [Errno 2] Failed to open the uinput device: No such file or directory. Perhaps load the uinput kernel module first?
xauth:  /home/Theta/.Xauthority not writable, changes will be ignored
xauth:  /home/Theta/.Xauthority not writable, changes ignored
_XSERVTransSocketCreateListener: failed to bind listener
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: failed to create listener for unix
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
2023-05-24 23:19:01,000 Error: failed to connect to display :539
2023-05-24 23:19:01,000  could not connect to X server on display ':539' after 3 seconds
```
5. Make sure that the obsidian.profile is created properly, check whether you have the electron profile also.
![Screenshot_2023-05-25_03-21-26](https://github.com/Amir1453/obsidicrypt/assets/43509639/0684f670-04d4-46cc-b8eb-d01d17be6fe0)
6. If nothing works, uninstall Xpra and run the firejail command again. It will ask you to download either Xpra or Xephyr, try installing Xephyr and see if it works for you.
I can try that but Xpra actually did work, it only broke later when I was trying to get it to also work with the KeepassXC profile.
![Screenshot_2023-05-23_22-58-50](https://github.com/Amir1453/obsidicrypt/assets/43509639/e5449add-2bdd-4f87-b357-5a3e53124a7b)
This is a screenshot showing the notification that appeared whenever I launched Obsidian before I somehow broke Xpra and it stopped being able to launch with the `--X11` flag. 
7. If nothing works, I would suggest creating an issue in the firejail repository.
Okay.

When I was setting it up to work with KeePassXC I saw in the logs that there was a missing uinput module and a few other modules so I installed them, that might have something to do with why it broke. Before I installed the modules I used a terminal with X11=xpra and my keyboard was still visible. I followed [this guide](https://firejail.wordpress.com/documentation-2/x11-guide/) to test that.

**Comment by Amir1453** [comment]
Hello, quick question. I am guessing KeepassXC is running when you are trying to run the profile right? Judging by `/run/user/1000/xpra/:100.log`, there might be a problem with Xpra instead of firejail. Try to turn off KeepassXC if it is running, and try starting xpra.

You probably changed the firefox.desktop file, since when running `DISPLAY=:100 firefox` firejail also starts. Can you please try with a program that is not firejailed? There might be a difference.
